services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL:-gemma3:1b-it-qat}
    entrypoint: /entrypoint.sh
    ports:
      - "11434:11434"
    restart: unless-stopped
    networks:
     - chla_net
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 180s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8080:5000"
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=http://ollama:11434
    networks:
    - chla_net
    depends_on:
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s

networks:
  chla_net:
    driver: bridge

volumes:
  ollama_data: