services:
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama_data:/root/.ollama
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    networks:
      - chla_net
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 45s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=ollama
      - PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - ollama
    networks:
      - chla_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - chla_net

networks:
  chla_net:
    driver: bridge

volumes:
  ollama_data: